---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
spec:
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.path }}
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  storageClassName: ""


